<?php
// $Id: feeds_git_fetcher.module,v 1.1.4.1 2011/02/05 18:12:18 twistor Exp $

define("GIT_PATH","/usr/bin/git");

/**
 * Implements hook_feeds_plugins().
 */
function feeds_git_fetcher_feeds_plugins() {
  $info = array();
  $info['FeedsGITFetcher'] = array(
    'name'        => t('GIT Repository Fetcher'),
    'description' => t('Fetch a remote GIT Repository and clone locally.'),
    'handler' => array(
      'parent' => 'FeedsFetcher',
      'class'  => 'FeedsGITFetcher',
      'file'   => 'FeedsGITFetcher.inc',
      'path'   => drupal_get_path('module', 'feeds_git_fetcher')
    ),
  );
  return $info;
}

/**
 * Implements hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function feeds_git_fetcher_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
